---
title: "2021-11-29-ST558-Last-Blog"
author: "Ilana Feldman"
date: "11/29/2021"
---

```{r eval = FALSE, echo = FALSE}
rmarkdown::render("./_Rmd/2021-11-29-ST558-Last-Blog.Rmd",
                  output_format = "github_document",
                  output_dir = "./_posts/",
                  output_options = list(html_preview = FALSE)
)
```

In the three and a half months since the start of the semester, my views on what a data scientist does, or who can accomplish the tasks of a data scientist, have not changed much. Statisticians, who collect, analyze, and draw conclusions from raw data, *could* help bridge the gap between the theoretical and the practical with their work, but the scope of a project is often enough such that it makes sense to have multiple collaborators, at least one of who's as well-versed as possible in current machine learning techniques and in statistics that they can bridge the gap. R seems like a perfectly capable tool for doing so - it's possible to configure R such that it runs more quickly and efficiently, and in a contained environment, we don't need to work with a complicated outside API, which is one of R's bigger weaknesses. 

On a personal level, I've found myself using R more often in the last few months for organizing data for my "fun" projects. In the past, I'd use Google Sheets, but it's often inefficient for running calculations or simulations on a large scale, and isn't able to handle larger amounts of data at all. Additionally, I've learned about features such as Projects that allow me to separate these projects from each other and my classwork. In the future, I'm hoping that I'll be able to use some of these organizational tools to help me organize my projects before I start working on them - my biggest issue is definitely not knowing when or where I'll even start working on a project such as the three in this class, the latter of which I still haven't begun, and R provides such a wide variety of ways to tackle this problem that there's bound to be ways to improve on my current methods.
